version: "3.5"
services:
  php:
    container_name: "${PROJECT_NAME}_php"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - ${PROJECT_PATH}:/var/www/html:cached
    depends_on:
      - mysql

  mysql:
    container_name: "${PROJECT_NAME}_db"
    image: mysql:8
    hostname: mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql:rw
      # SQL файлы для инициализации
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
volumes:
  db_data:
    name: ${PROJECT_NAME}_db_data
