version: "3.5"
services:
  web:
    image: nginx
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - "83:80"
    links:
      - php
      - mysql
    volumes:
      - ./docker/nginx/server.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html:cached

  php:
    container_name: "${PROJECT_NAME}_php"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html:cached

  mysql:
    container_name: "${PROJECT_NAME}_db"
    image: mysql:8
    hostname: mysql
    environment:
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_ROOT_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql:rw
volumes:
  db_data:
